[toolchain]

[features]
resolution = true
skip-lint = false

[programs.localnet]
bubblegum_common_collection = "4hE1H9kAU1S28ZL4x9264G9SUFEGvEVt2yv1BDChZ8fa"

[registry]
url = "https://api.apr.dev"

[[test.genesis]]
address = "BGUMAp9Gq7iTEuizy4pqaxsTyUCBK68MDfK752saRPUY"
program = "./dumped_programs/bubblegum.so"

[[test.genesis]]
address = "noopb9bkMVfRPU8AsbpTUg8AQkHtKwMYZiFUjNRtMmV"
program = "./dumped_programs/logWrapper.so"

[[test.genesis]]
address = "cmtDvXumGCrqC1Age74AVPhSRVXJMd8PJS91L8KbNCK"
program = "./dumped_programs/compressionProgram.so"

[provider]
cluster = "Localnet"
wallet = "~/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
